### PR TITLE
Polykey-Docs: Getting-Started-Documentation 

### LINKED ISSUE #9: Polykey-Docs: Flesh out Polykey-CLI Tutorials "Getting Started"
This tutorial should provide a run through of Polykey's functionality. It needs to start from the begnning beginning of using PK and provide a practical outcome with using PK.

PR to track Tasks #6-9 -> [https://github.com/MatrixAI/Polykey-Docs/pull/72](https://github.com/MatrixAI/Polykey-Docs/pull/72)

### Tasks

- [X] 0\. Revamp [Readme.md](http://Readme.md) of polykey-cli
- [X] 1\. Revamp docs/tutorials/polykey-cli to outline the "getting started" pages that fall under this section - [Polykey-Docs CLI Tutorial: Add Getting Started Section  #52](https://github.com/MatrixAI/Polykey-Docs/issues/52)
- [X] 2\. Installation Section
- [X] 3\. Bootstrapping [https://github.com/MatrixAI/Polykey-Docs/issues/53](https://github.com/MatrixAI/Polykey-Docs/issues/53) - Will need to do a re-check \~ 15 min 
- [X] 4\. Managing Vaults [https://github.com/MatrixAI/Polykey-Docs/issues/54](https://github.com/MatrixAI/Polykey-Docs/issues/54) - Will need to do some reformatting to match Managing secret's \~45 min 
- [X] 5\. Managing Secrets [https://github.com/MatrixAI/Polykey-Docs/issues/55](https://github.com/MatrixAI/Polykey-Docs/issues/55)
       - We can provide an example of injecting secrets into the environment here
- [x] 6\. Claiming Identity [https://github.com/MatrixAI/Polykey-Docs/issues/56](https://github.com/MatrixAI/Polykey-Docs/issues/56) -> \~1 hour
- [x] 7\. Connecting to other Nodes [https://github.com/MatrixAI/Polykey-Docs/issues/57](https://github.com/MatrixAI/Polykey-Docs/issues/57) - What if you have no friends? - \~2.5 hours Let's make up a friend. By creating a 2nd node (for a separate node path) locally. In this case, both nodes will claim the same identity, so then you're sharing a vault between your own nodes.
- [x] 8\. Sharing Vaults [https://github.com/MatrixAI/Polykey-Docs/issues/58](https://github.com/MatrixAI/Polykey-Docs/issues/58) - \~3 hours <br>      - Share Vault with 2nd node
- [ ] 9\. Secrets ENV command [https://github.com/MatrixAI/Polykey-Docs/issues/59](https://github.com/MatrixAI/Polykey-Docs/issues/59)\~ \~2 hours 

Once all these pages have been completed. We can push. However, the flow from page-to-page varies somewhat and i'd like to use a more consistent approach so it will require a revamp ticket after this.

### PR DESCRIPTION
**Pull request by CryptoTotalWar**
### Description

This PR will be for fleshing out the tutorials / Polykey-CLI 

### Issues Fixed

* Fixes #9 

### Tasks

- [x] 1. review README for adding new pages to reference
- [x] 2. switch the order of the pages

### Final checklist

* [ ] Domain specific tests
* [ ] Full tests
* [ ] Updated inline-comment documentation
* [ ] Lint fixed
* [ ] Squash and rebased
* [ ] Sanity check the final build

### CODE REVIEW

**Comment by CMCDragonkai** [comment]
See https://github.com/MatrixAI/Polykey-Docs/pull/71#issuecomment-2132605153.

And also ensure that you be rebase squashed and follow conventional commit standard: https://www.conventionalcommits.org/en/v1.0.0/

**Comment by CMCDragonkai** [comment]
Current state of staging is now in production. Ignore the current staging failure is that occurs because the branch is already up to date.

**Comment by CryptoTotalWar** [comment]
Just rebased this feature branch off of the staging branch which had changes.

**Comment by CryptoTotalWar** [comment]
For the managing env variables I am inclined to create a simple demo project that would typically have a .env file and move these env variables to a vault instead that will be injected. 

Following the following guidelines: https://www.phind.com/search?cache=vjacfmn8ykb7e652jukukkxm

**Comment by CMCDragonkai** [comment]
This PR is not triggering the CI because it doesn't have the right branch name it should be `feat-X`.

**Comment by CMCDragonkai** [comment]
1. Tasks need to be specified - and need to be specific.
2. They need to be ticked off as you're working on them
3. They represent what still needs to be done - can you delegate this to another person and they would understand what still needs to be done?
4. This represents implementation not requirements - so they much more specific
5. Don't leave hanging tasks.
6. Review the checklist
7. Make sure you're commenting when a PR closes another PR

**Comment by CryptoTotalWar** [comment]
Closing PR as it had the incorrect branch name, created a new PR for this here https://github.com/MatrixAI/Polykey-Docs/pull/75

**Pull request closed without merging**
