### PR TITLE
Feature dev community contribution guides

### PR DESCRIPTION
**Pull request by CryptoTotalWar**
### Description
This PR introduces a new guide for developers who want to contribute to the Polykey repository. It outlines the necessary setup steps for macOS, Windows, and Linux users, including the installation of development tools and the configuration of development environments.

1. 1 new folder called "community contributions" created and added under "development-guide"
2. 1 new file under this new folder called "contributor-setup-guide" outlining the global dev dependencies and requirements for devs to get started with cloning the repo. 
Note: this may be redundant as we would probably expect most dev contributors to to be more high-level and either have already done these steps or do not require our documentation to help them. 
Note: I left the Windows and Linux part blank because I only know the process required for Mac 
4. I created an empty MD file called "contribution-guidelines-and-standards" where i expect we would have a blurb outlining our expectations of devs who want to contribute, the workflow standards, naming conventions, etc. 

### Issues Fixed

None, this was a test run 

### Tasks

- ~~[ ] 1. One new folder called "community contributions" created and added under "development-guide"~~
- ~~[ ] 2. 1 new file under this new folder called "contributor-setup-guide" outlining the global dev dependencies and requirements for devs to get started with cloning the repo.~~ 
- Note: this may be redundant as we would probably expect most dev contributors to to be more high-level and either have already done these steps or do not require our documentation to help them. 
- Note: I left the Windows and Linux part blank because I only know the process required for Mac 
- [ ] 3. I created an empty MD file called "contribution-guidelines-and-standards" where i expect we would have a blurb outlining our expectations of devs who want to contribute, the workflow standards, naming conventions, etc. 
- standard convention for commit messages in the OSS workflow of this repo. [Context](https://www.conventionalcommits.org/en/v1.0.0/) 

### Final checklist

* [ ] Domain specific tests
* [ ] Full tests
* [ ] Updated inline-comment documentation
* [ ] Lint fixed
* [ ] Squash and rebased
* [ ] Sanity check the final build

### CODE REVIEW

**Comment by CMCDragonkai** [comment]
Since this is based off the other PR, best to target that PR branch.

Also we use conventional commits as our commit messages https://www.conventionalcommits.org/en/v1.0.0/

**Comment by CMCDragonkai** [comment]
Screenshot_2024-03-07-15-42-47-40_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by CryptoTotalWar** [comment]
I completely forgot to switch the default branch for the PR (in gh) to target the PR branch I cloned off of. 
And I'll reference https://www.conventionalcommits.org/en/v1.0.0/ for context next time making commit messages. 

- Pablo

**Comment by CryptoTotalWar** [comment]
target branch for PR changed.

**Comment by CMCDragonkai** [comment]
I think it's best to put everything into #33 for now since you're taking over it rather than 2 PRs. So I'm closing this, and migrating your current WIP over there.

**Pull request closed without merging**
