### PR TITLE
Footer and header in-line with main website

### PR DESCRIPTION
**Pull request by addievo**
### Description

Refactors the header and footer to be in-line with PK.com 3.0. 

### Tasks

- [x] 1. Header
- [x] 2. Footer

### Final checklist

* [x] Lint fixed
* [x] Squash and rebased
* [x] Sanity check the final build

### CODE REVIEW

**Comment by CMCDragonkai** [comment]
Actually I think I might want to keep our footer here and instead make the main website use this footer.

**Comment by CMCDragonkai** [comment]
Did you lint this? Is this why lots of things are changed?

**Comment by CMCDragonkai** [comment]
Can you try separating the linting commit from the actual nominal change.

**Comment by addievo** [comment]
Deleting this MR and branch and redoing as we changed PK.com footer to the one from Docs

**Pull request closed without merging**
