### PR TITLE
Comprehensive Getting Started Guide 

### LINKED ISSUE #9: Polykey-Docs: Flesh out Polykey-CLI Tutorials "Getting Started"
This tutorial should provide a run through of Polykey's functionality. It needs to start from the begnning beginning of using PK and provide a practical outcome with using PK.

PR to track Tasks #6-9 -> [https://github.com/MatrixAI/Polykey-Docs/pull/72](https://github.com/MatrixAI/Polykey-Docs/pull/72)

### Tasks

- [X] 0\. Revamp [Readme.md](http://Readme.md) of polykey-cli
- [X] 1\. Revamp docs/tutorials/polykey-cli to outline the "getting started" pages that fall under this section - [Polykey-Docs CLI Tutorial: Add Getting Started Section  #52](https://github.com/MatrixAI/Polykey-Docs/issues/52)
- [X] 2\. Installation Section
- [X] 3\. Bootstrapping [https://github.com/MatrixAI/Polykey-Docs/issues/53](https://github.com/MatrixAI/Polykey-Docs/issues/53) - Will need to do a re-check \~ 15 min 
- [X] 4\. Managing Vaults [https://github.com/MatrixAI/Polykey-Docs/issues/54](https://github.com/MatrixAI/Polykey-Docs/issues/54) - Will need to do some reformatting to match Managing secret's \~45 min 
- [X] 5\. Managing Secrets [https://github.com/MatrixAI/Polykey-Docs/issues/55](https://github.com/MatrixAI/Polykey-Docs/issues/55)
       - We can provide an example of injecting secrets into the environment here
- [x] 6\. Claiming Identity [https://github.com/MatrixAI/Polykey-Docs/issues/56](https://github.com/MatrixAI/Polykey-Docs/issues/56) -> \~1 hour
- [x] 7\. Connecting to other Nodes [https://github.com/MatrixAI/Polykey-Docs/issues/57](https://github.com/MatrixAI/Polykey-Docs/issues/57) - What if you have no friends? - \~2.5 hours Let's make up a friend. By creating a 2nd node (for a separate node path) locally. In this case, both nodes will claim the same identity, so then you're sharing a vault between your own nodes.
- [x] 8\. Sharing Vaults [https://github.com/MatrixAI/Polykey-Docs/issues/58](https://github.com/MatrixAI/Polykey-Docs/issues/58) - \~3 hours <br>      - Share Vault with 2nd node
- [ ] 9\. Secrets ENV command [https://github.com/MatrixAI/Polykey-Docs/issues/59](https://github.com/MatrixAI/Polykey-Docs/issues/59)\~ \~2 hours 

Once all these pages have been completed. We can push. However, the flow from page-to-page varies somewhat and i'd like to use a more consistent approach so it will require a revamp ticket after this.

### PR DESCRIPTION
**Pull request by CryptoTotalWar**
### Description
A comprehensive "getting-started" guide will be developed to walk users through all the basic commands for using Polykey, mirroring the demo video. Additionally, this PR will address missing content and structural elements in the documentation, particularly in the main entry page and the tutorials section.

### Issues Fixed
* Fixes #9 

### Tasks - should specifically describe the pages or sections of content that need to be addressed 

1. **[Polykey-Docs Entry Page](https://polykey.com/docs/) - Half Baked**
   - [ ] Add "Features Section" - Detail the core features of Polykey.
   - [ ] Add "Comparison to other tools" - Compare Polykey with similar tools in the market.
   - [ ] Ensure the entry page is represented in the left navigation bar.

2. **[PK-Tutorials Page](https://polykey.com/docs/tutorials) - Mostly Baked**
   - [ ] Provide a high-level overview linking to Polykey CLI & Polykey Core.
   - [ ] Specify the difference and purpose of both Polykey CLI & Polykey Core.
   - [x] Decide on the relevance of Desktop & Mobile Versions in the tutorials -> [Action Taken](https://github.com/MatrixAI/Polykey-Docs/pull/42/commits/161b8c980e9749024abb135dddc678a232bdb887)
   
3. **[Polykey CLI](https://polykey.com/docs/tutorials/polykey-cli)**
   - [ ] Mention the high-level overview of the CLI.
   - [ ] Integrate and describe the video guide to get started with Polykey.
   - [ ] Create a comprehensive "Getting Started" guide that will walk users through all the basic commands, mirroring the demo video.
   
4. **Other Tutorial Sections**
   - [x] [Installation](https://polykey.com/docs/tutorials/polykey-cli/installation) - mostly done.
   - [ ] Bootstrap Keypair - Document the process.
   - [ ] Managing Vaults - Provide step-by-step guidance.
   - [ ] Managing Secrets - Detail procedures and best practices.
   - [ ] Connecting to other Nodes - Explain how to connect Polykey nodes.
   - [ ] Claiming Digital Identities - Describe the steps and importance.
   - [ ] Sharing Vaults - Outline methods to securely share vaults.

### Final checklist

* [ ] Domain specific tests
* [ ] Full tests
* [ ] Updated inline-comment documentation
* [ ] Lint fixed
* [ ] Squash and rebased
* [ ] Sanity check the final build

### CODE REVIEW

**Comment by CryptoTotalWar** [comment]
Need someone to review the following commit [7e1f0314c4b6d66450e99f34c9fda2f23bee1ffa](https://github.com/MatrixAI/Polykey-Docs/pull/42/commits/7e1f0314c4b6d66450e99f34c9fda2f23bee1ffa)

- I am attempting to add the demo video to the getting-started page. I attempted to make this work by adding some changes in the code (you can see in this commit). The video will play successfully but when pausing or fast forwarding it glitches out. 

- So it's possible that the changes i made in this commit are probably not the correct way to go about adding the video in the documentation. 

- @amydevs maybe you can also show me on Thursday the correct way to do this.

**Comment by CMCDragonkai** [comment]
Best way to add videos, is to do a vimeo embed. All of our "corporate videos" are put into Vimeo - and then you can just embed them there. There are settings in vimeo that limit where things can be embedded, but it's easy enough to add in domain rules such as `polykey.com`.

**Comment by CryptoTotalWar** [comment]
I did a git reset to the previous commit (incorrectly adding video) and did a git push force for the newly committed change that adds the video using vimeo embed. Pretty straight forward.

**Comment by CryptoTotalWar** [comment]
In the [latest commit](https://github.com/MatrixAI/Polykey-Docs/pull/42/commits/161b8c980e9749024abb135dddc678a232bdb887), I commented out the Polykey Mobile and Polykey Desktop section from displaying on the navbar because I feel they can be distracting for our current phase of development. I did not delete them, I just hid them from the Navbar because i want the attention to be directed towards Polykey CLI and Polykey Core which are released whereas Mobile and Desktop, this was the only info we have for them currently. 

image
image

We can still draft content for Polykey Mobile and Desktop but the point is it have it hidden from the nav bar until we have something more substantial to show. 

The navbar is much cleaner when you remove it (firstly) 
image

On a separate issue, I want to include the Polykey/Docs page on the navbar on top of tutorials. So there should also be a navigation arrow to go back to it. Currently, a user can only go back to the Docs entry page by clicking on the tab instead of finding it on the navbar. 

image

**Comment by CryptoTotalWar** [comment]
Roger is talking about having a link for people to "improve the docs" 

Link to the source code that represent that page. This is easy to do. There might be a docusourus plugin that can do this. Research a plugin for link to source. 

This would be a way that users who may have a suggestion for improving the docs. 

image

clicking on the edit this page 

https://github.com/facebook/docusaurus/blob/main/website/docs/introduction.mdx

If it could go from edit to blob
It would work better

**Comment by CryptoTotalWar** [comment]
Recommendation to have separate PRs for 1,2,3.

**Comment by CryptoTotalWar** [comment]
REMINDERS - Make this PR an "Epic" and make small PRs off of each task.

**Comment by CMCDragonkai** [comment]
Due to #36, this needs to be recreated from scratch - starting by checking out staging (ensure you are on the latest), and recreate a new PR here.

**Pull request closed without merging**
